version: "3"

services: 
  app:
    build:
      context: ./
      dockerfile: ./dockerfiles/node.dockerfile
    command: npm run start
    ports: 
      - "3000:3000"
    volumes: 
      - .:/usr/app
    depends_on: 
      - mongodb  
    
  mongodb:
    image: mongo
    ports: 
      - "27017:27017"
    volumes: 
      - data-volume:/data/db

volumes: 
  data-volume:
